Vitorschelb/50 implement pos onboarding flow
podcodar/app pull request #59
Opened 2023-08-28 20:17 UTC by vitorschelb

# Description

This PR creates a list with no dependencies tasks and assign to user

- Ref dependencies tasks on seed
-  Create class TasksDAO on tasks.dao.ts with method to look for all tasks that don't depend on other tasks.
- Creates method on DB to assing these tasks to the user (UserTasks table)
-  Assign the no dependencies tasks to the user on the pos onboarding route flow

2023-08-29 12:27 UTC, marco-souza approved these changes
Nice one! 

I left some minor style comments, but LGTM!

2023-08-29 12:27 UTC, marco-souza commented on src/app/api/onboarding/route.ts
> +    await user.assignTasksToUser(userData?.id, tasksWithNoDependencies);
```suggestion
    await user.assignTasksToUser(userData.id, tasksWithNoDependencies);
```

2023-08-29 12:27 UTC, marco-souza commented on src/shared/db.ts
> +      userId: userId,
```suggestion
      userId,
```

2023-08-29 12:27 UTC, marco-souza commented
we still need to resolve the integration test before merging it

2023-08-29 12:28 UTC, marco-souza commented
Also, friendly reminder to update the PR title, to something more readable

2023-08-30 18:01 UTC, marco-souza requested changes

2023-08-30 18:01 UTC, marco-souza commented on src/tests/db.test.ts
> +      expect(userTasks.length);
I think you removed the assert here

```suggestion
      expect(userTasks.length).toHaveLength(0);
```

2023-08-30 18:39 UTC, vitorschelb commented on src/tests/db.test.ts
> +      expect(userTasks.length);
expect(userTasks).toHaveLength(0)

2023-08-30 18:44 UTC, marco-souza approved these changes
![The Way](https://media.tenor.com/AwaCy9sb94gAAAAC/baby-yoda-this-is-the-way.gif)

2023-08-30 18:45 UTC, merged